name: Commitlint
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: "Commitlint"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Commitlint"
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: "./.commitlintrc.yml"
          failOnWarnings: true
